name: KMP
channels:
  - pytorch
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - backcall=0.2.0=py_0
  - blas=1.0=mkl
  - bzip2=1.0.8=h7b6447c_0
  - ca-certificates=2020.6.24=0
  - certifi=2020.6.20=py37_0
  - cudatoolkit=10.2.89=hfd86e86_1
  - decorator=4.4.2=py_0
  - ffmpeg=4.2.2=h20bf706_0
  - freetype=2.10.2=h5ab3b9f_0
  - gmp=6.1.2=h6c8ec71_1
  - gnutls=3.6.5=h71b1129_1002
  - intel-openmp=2020.1=217
  - ipython=7.15.0=py37_0
  - ipython_genutils=0.2.0=py37_0
  - jedi=0.17.0=py37_0
  - jpeg=9b=h024ee3a_2
  - lame=3.100=h7b6447c_0
  - ld_impl_linux-64=2.33.1=h53a641e_7
  - libedit=3.1.20181209=hc058e9b_0
  - libffi=3.3=he6710b0_1
  - libgcc-ng=9.1.0=hdf63c60_0
  - libgfortran-ng=7.3.0=hdf63c60_0
  - libopus=1.3.1=h7b6447c_0
  - libpng=1.6.37=hbc83047_0
  - libstdcxx-ng=9.1.0=hdf63c60_0
  - libtiff=4.1.0=h2733197_1
  - libvpx=1.7.0=h439df22_0
  - lz4-c=1.9.2=he6710b0_0
  - mkl=2020.1=217
  - mkl-service=2.3.0=py37he904b0f_0
  - mkl_fft=1.1.0=py37h23d657b_0
  - mkl_random=1.1.1=py37h0573a6f_0
  - ncurses=6.2=he6710b0_1
  - nettle=3.4.1=hbb512f6_0
  - ninja=1.9.0=py37hfd86e86_0
  - numpy-base=1.18.1=py37hde5b4d6_1
  - olefile=0.46=py37_0
  - openh264=2.1.0=hd408876_0
  - openssl=1.1.1g=h7b6447c_0
  - parso=0.7.0=py_0
  - pexpect=4.8.0=py37_0
  - pickleshare=0.7.5=py37_0
  - pillow=7.1.2=py37hb39fc2d_0
  - pip=20.0.2=py37_3
  - prompt-toolkit=3.0.5=py_0
  - prompt_toolkit=3.0.5=0
  - ptyprocess=0.6.0=py37_0
  - pygments=2.6.1=py_0
  - python=3.7.7=hcff3b4d_5
  - pytorch=1.5.1=py3.7_cuda10.2.89_cudnn7.6.5_0
  - readline=8.0=h7b6447c_0
  - setuptools=47.1.1=py37_0
  - six=1.15.0=py_0
  - sqlite=3.31.1=h62c20be_1
  - tk=8.6.8=hbc83047_0
  - torchvision=0.6.1=py37_cu102
  - traitlets=4.3.3=py37_0
  - wcwidth=0.2.4=py_0
  - wheel=0.34.2=py37_0
  - x264=1!157.20191217=h7b6447c_0
  - xz=5.2.5=h7b6447c_0
  - zlib=1.2.11=h7b6447c_3
  - zstd=1.4.4=h0b5b093_3
  - pip:
    - absl-py==0.9.0
    - ase==3.20.1
    - cachetools==4.1.0
    - cffi==1.14.2
    - chardet==3.0.4
    - cryptography==3.1
    - cssselect==1.1.0
    - cssutils==1.0.2
    - cycler==0.10.0
    - cython==0.29.20
    - filelock==3.0.12
    - fire==0.3.1
    - flake8==3.8.3
    - future==0.18.2
    - gdown==3.11.1
    - google-auth==1.17.2
    - google-auth-oauthlib==0.4.1
    - googledrivedownloader==0.4
    - grpcio==1.29.0
    - h5py==2.10.0
    - huepy==1.2.1
    - idna==2.9
    - imageio==2.8.0
    - importlib-metadata==1.6.1
    - isodate==0.6.0
    - isort==4.3.21
    - jeepney==0.4.3
    - jinja2==2.11.2
    - joblib==0.16.0
    - keyring==21.4.0
    - kiwisolver==1.2.0
    - knockknock==0.1.8.1
    - llvmlite==0.34.0
    - lxml==4.5.2
    - markdown==3.2.2
    - markupsafe==1.1.1
    - matplotlib==3.2.2
    - matrix-client==0.3.2
    - mccabe==0.6.1
    - networkx==2.4
    - numba==0.51.0
    - numpy==1.18.5
    - oauthlib==3.1.0
    - opencv-python==4.2.0.34
    - pandas==1.1.1
    - premailer==3.7.0
    - protobuf==3.12.2
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - pycodestyle==2.6.0
    - pycparser==2.20
    - pyflakes==2.2.0
    - pyjwt==1.7.1
    - pyparsing==2.4.7
    - pysocks==1.7.1
    - python-dateutil==2.8.1
    - python-telegram-bot==12.8
    - pytz==2020.1
    - pyyaml==5.3.1
    - rdflib==5.0.0
    - requests==2.24.0
    - requests-oauthlib==1.3.0
    - rsa==4.6
    - scikit-learn==0.23.2
    - scipy==1.4.1
    - secretstorage==3.1.2
    - tb-nightly==2.3.0a20200615
    - tensorboard-plugin-wit==1.6.0.post3
    - termcolor==1.1.0
    - threadpoolctl==2.1.0
    - torch-cluster==1.5.7
    - torch-geometric==1.6.1
    - torch-scatter==2.0.5
    - torch-sparse==0.6.7
    - torch-spline-conv==1.2.0
    - tornado==6.0.4
    - tqdm==4.46.1
    - twilio==6.45.1
    - urllib3==1.25.9
    - werkzeug==1.0.1
    - yacs==0.1.7
    - yagmail==0.12.233
    - yapf==0.30.0
    - zipp==3.1.0