adam:
  beta1: 0.9
  beta2: 0.999
cuhk03:
  classic_split: false
  labeled_images: false
  use_metric_cuhk03: false
data:
  combineall: false
  height: 256
  load_train_targets: false
  norm_mean:
  - 0.485
  - 0.456
  - 0.406
  norm_std:
  - 0.229
  - 0.224
  - 0.225
  root: data
  save_dir: logs/v0.0.0/
  sources:
  - mars
  split_id: 0
  targets:
  - mars
  transforms:
  - random_flip
  - random_erase
  type: video
  width: 128
  workers: 4
loss:
  name: softmax
  softmax:
    label_smooth: true
  triplet:
    margin: 0.3
    weight_t: 1.0
    weight_x: 0.0
market1501:
  use_500k_distractors: false
model:
  load_weights: ''
  name: pcb_p4
  pretrained: true
  resume: ''
rmsprop:
  alpha: 0.99
sampler:
  num_instances: 4
  train_sampler: RandomSampler
  train_sampler_t: RandomSampler
sgd:
  dampening: 0.0
  momentum: 0.9
  nesterov: true
test:
  batch_size: 32
  dist_metric: euclidean
  eval_freq: 5
  evaluate: false
  normalize_feature: false
  ranks:
  - 1
  - 5
  - 10
  - 20
  rerank: false
  start_eval: 0
  visrank: false
  visrank_topk: 10
train:
  base_lr_mult: 0.1
  batch_size: 16
  fixbase_epoch: 0
  gamma: 0.1
  lr: 0.003
  lr_scheduler: single_step
  max_epoch: 60
  new_layers:
  - classifier
  open_layers:
  - classifier
  optim: adam
  print_freq: 20
  seed: 1
  staged_lr: false
  start_epoch: 0
  stepsize:
  - 20
  weight_decay: 5.0e-4
video:
  pooling_method: avg
  sample_method: evenly
  seq_len: 16

